# This is a basic workflow to help you get started with Actions

name: dotnet_ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "prod" branch
  push:
    paths:
      - 'SchoolApp/SchoolApi/**'
    branches:
      - prod
      - test
      - develop
  pull_request:
    paths:
      - 'SchoolApp/SchoolApi/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore SchoolApp/SchoolApi/SchoolApi.csproj
    - name: Build
      run: dotnet build --no-restore SchoolApp/SchoolApi/SchoolApi.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal SchoolApp/SchoolApi/SchoolApi.csproj
